theme: minima
title: My Awesome Family History
author: Q.L. Davis
email: davisl_quentin@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  This site will explore and tell about all the interesting people in my family's history. 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
